- resources/assets/enderio/config/SAGMillRecipes_Core.xml
- src/main/java/crazypants/enderio/config/Config.java
- src/main/java/crazypants/enderio/machine/crusher/CrusherRecipeManager.java
The SAG Mill thought it was the Alloy Smelter - silly thing :)
> fixed machine name in log message

- src/main/java/crazypants/enderio/machine/farm/TileFarmStation.java
Also fixed an edge case where crops could be inserted into the tool slot on the tick that the tool broke
> Farm Station respects Tinker's Tools

- src/main/java/crazypants/enderio/machine/monitor/TilePowerMonitor.java
Required for asiekierka/Computronics#99
> Made Power Monitor Engine control accessible

- src/main/java/cofh/api/inventory/IInventoryConnection.java
- src/main/java/cofh/api/inventory/IInventoryHandler.java
- src/main/java/cofh/api/inventory/IInventoryRetainer.java
- src/main/java/cofh/api/inventory/package-info.java
- src/main/java/crazypants/enderio/conduit/item/ItemConduit.java
> Implement IInventoryConnection on ItemConduits

- resources/assets/enderio/lang/en_US.lang
- src/main/java/crazypants/enderio/conduit/gui/item/ExistingItemFilterGui.java
- src/main/java/crazypants/enderio/conduit/gui/item/PacketExistingItemFilterSnapshot.java
- src/main/java/crazypants/enderio/conduit/item/filter/ExistingItemFilter.java
- src/main/java/crazypants/enderio/conduit/item/filter/ItemExistingItemFilter.java
As a side effect of this - taking a snapshot or merging takes the current filter mode into account
> #1458 Add button to merge inventory content with existing snapshot

- resources/assets/enderio/config/PoweredSpawnerConfig_Core.json
- resources/assets/enderio/lang/en_US.lang
- src/main/java/crazypants/enderio/EnderIO.java
- src/main/java/crazypants/enderio/config/Config.java
- src/main/java/crazypants/enderio/entity/EntityWitherSkeleton.java
- src/main/java/crazypants/enderio/entity/SkeletonHandler.java
allows it to work properly in powered spawner, plus it's really annoying
> Unique Wither Skeleton Entity

- resources/mcmod.info
- resources/pack.mcmeta
Also, added pack.mcmeta and added tterrag to author list. If you against it tterrag feel free to close it.
> Fixed authorList in mcmod.info

- resources/assets/enderio/lang/pt_BR.lang
So, here it is - brazilian portuguese translation!
rushed after that not-read-changelog-crash thingy
now with 87,66% more translated witty tooltips!
/after a quick edit, now up to date with the en_US (thx diff checker)/
> pt_BR translations and shtuff

- resources/assets/enderio/lang/en_US.lang
- resources/assets/enderio/lang/ru_RU.lang
- src/main/java/crazypants/enderio/item/KeyTracker.java
- src/main/java/crazypants/enderio/nei/AlloySmelterRecipeHandler.java
- src/main/java/crazypants/enderio/nei/EnchanterRecipeHandler.java
- src/main/java/crazypants/enderio/nei/SagMillRecipeHandler.java
- src/main/java/crazypants/enderio/nei/SliceAndSpliceRecipeHandler.java
- src/main/java/crazypants/enderio/nei/SoulBinderRecipeHandler.java
- src/main/java/crazypants/enderio/nei/VatRecipeHandler.java
Part of #1652 for some reason I can't localize Waila config. Also, deleted some double spaces and white spaces from en_US.lang. And also textures in entity folder still needed? I guess they was moved into Ender Zoo.
> Localized NEI and Keybinds

- resources/assets/enderio/lang/cs_CZ.lang
- resources/assets/enderio/lang/de_DE.lang
- resources/assets/enderio/lang/en_US.lang
- resources/assets/enderio/lang/fr_FR.lang
- resources/assets/enderio/lang/ko_KR.lang
- resources/assets/enderio/lang/pl_PL.lang
- resources/assets/enderio/lang/pt_BR.lang
- resources/assets/enderio/lang/ru_RU.lang
- resources/assets/enderio/lang/zh_CN.lang
- resources/assets/enderio/lang/zh_TW.lang
- src/main/java/crazypants/enderio/conduit/gui/LiquidSettings.java
- src/main/java/crazypants/enderio/config/Config.java
- src/main/java/crazypants/enderio/machine/crafter/GuiCrafter.java
- src/main/java/crazypants/enderio/machine/generator/combustion/GuiCombustionGenerator.java
- src/main/java/crazypants/enderio/machine/generator/zombie/BlockZombieGenerator.java
- src/main/java/crazypants/enderio/machine/generator/zombie/GuiZombieGenerator.java
- src/main/java/crazypants/enderio/machine/gui/GuiMachineBase.java
- src/main/java/crazypants/enderio/machine/gui/GuiPoweredMachineBase.java
- src/main/java/crazypants/enderio/machine/hypercube/TileHyperCube.java
- src/main/java/crazypants/enderio/machine/spawner/GuiPoweredSpawner.java
- src/main/java/crazypants/enderio/machine/transceiver/BlockTransceiver.java
- src/main/java/crazypants/enderio/machine/transceiver/gui/ChannelTab.java
- src/main/java/crazypants/enderio/machine/transceiver/gui/FilterTab.java
- src/main/java/crazypants/enderio/machine/transceiver/gui/GeneralTab.java
- src/main/java/crazypants/enderio/machine/xp/GuiExperianceObelisk.java
> Localize GUIs

- src/main/java/crazypants/enderio/machine/killera/TileKillerJoe.java
- src/main/java/crazypants/enderio/machine/wireless/IWirelessCharger.java
- src/main/java/crazypants/enderio/machine/wireless/TileWirelessCharger.java
- src/main/java/crazypants/enderio/machine/wireless/WirelessChargedLocation.java
- src/main/java/crazypants/enderio/machine/wireless/WirelessChargerController.java
I created this while preparing wireless charger support for the farming station.
Could probably be helpful when a lot of wireless charger are in use (server).
> cache which wireless chargers are in range of a TE

- src/main/java/crazypants/enderio/item/ItemYetaWrench.java
This allows the use of shift left click in creative mode
> don't break conduits with the yeta wrench on left click

- src/main/java/crazypants/enderio/machine/alloy/ContainerAlloySmelter.java
Also remove a redundant if statement and made 2 fields final
> give achievements for smelting iron and cooking fish in the alloy smelter

- src/api/java/thaumcraft/api/crafting/IInfusionStabiliser.java
- src/main/java/crazypants/enderio/item/skull/BlockEndermanSkull.java
Just a minor PR to make it so Endermen heads act as stabilisers like all other mob heads
> Made endermen heads act as Thaumcraft infusion stabilisers 

- src/main/java/crazypants/enderio/conduit/gui/item/ItemSettings.java
* Tooltip for "Priority" field in item conduit GUI was off
> * Fixed tooltip position

- src/main/java/crazypants/enderio/machine/vacuum/TileVacuumChest.java
- src/main/java/crazypants/util/ItemUtil.java
* Behaves more like expected; existing stacks are filled first
* Unified code; only one implementationf for ISidedInventory and
IInventory
* Less resource intensive; objects are only created when really needed
> New way to insert items into inventories

- src/main/java/crazypants/enderio/item/darksteel/DarkSteelController.java
- src/main/java/crazypants/enderio/machine/hypercube/BlockHyperCube.java
- src/main/java/crazypants/enderio/machine/hypercube/Channel.java
- src/main/java/crazypants/enderio/machine/hypercube/GuiHyperCube.java
- src/main/java/crazypants/enderio/machine/hypercube/HyperCubeConfig.java
- src/main/java/crazypants/enderio/machine/hypercube/HyperCubeRegister.java
- src/main/java/crazypants/enderio/machine/hypercube/PacketAddRemoveChannel.java
- src/main/java/crazypants/enderio/machine/hypercube/PacketChannelList.java
- src/main/java/crazypants/enderio/machine/hypercube/PacketClientState.java
- src/main/java/crazypants/enderio/machine/hypercube/TileHyperCube.java
- src/main/java/crazypants/enderio/machine/transceiver/Channel.java
- src/main/java/crazypants/enderio/machine/transceiver/ClientChannelRegister.java
- src/main/java/crazypants/enderio/machine/transceiver/ServerChannelRegister.java
- src/main/java/crazypants/enderio/machine/transceiver/gui/ChannelTab.java
- src/main/java/crazypants/enderio/teleport/ITravelAccessable.java
- src/main/java/crazypants/enderio/teleport/TileTravelAnchor.java
- src/main/java/crazypants/util/PlayerUtil.java
The code works with offline mode as well
> Switched to storing UUID instead of username, with Offline Mode compatibility

- src/main/java/crazypants/enderio/item/darksteel/ItemDarkSteelAxe.java
> Fix for SideOnly-Error in DarkSteelAxe

- src/main/java/crazypants/enderio/enderface/BlockEnderIO.java
- src/main/java/crazypants/enderio/machine/transceiver/ClientChannelRegister.java
- src/main/java/crazypants/enderio/teleport/BlockTravelAnchor.java
Minor mistake in the UUID conversion fixed
> Fixed UUID showing up in denied message

- resources/assets/enderio/lang/en_US.lang
- src/main/java/crazypants/enderio/conduit/me/IMEConduit.java
- src/main/java/crazypants/enderio/conduit/me/MEConduit.java
- src/main/java/crazypants/enderio/waila/WailaCompat.java
This also stops displaying "0 / 0 RF" for other conduits which do not have Waila yet.
> only transmit required information for conduits, add used channels display for ME conduits

- src/main/java/crazypants/enderio/conduit/me/MEConduit.java
- src/main/java/crazypants/enderio/conduit/me/MEConduitGrid.java
Sadly I found no better solution - could be cleaned up once someone either fixes the AE2 API or finds it's magic decoder ring
> #1937 reconnect to P2P ME tunnels after chunk load

- src/main/java/crazypants/enderio/machine/buffer/TileBuffer.java
50% FPS drop from just a single buffer is a bit too much...
> Removed unnecessary client sync

- resources/assets/enderio/lang/en_US.lang
- src/main/java/crazypants/enderio/conduit/power/NetworkPowerManager.java
- src/main/java/crazypants/enderio/machine/capbank/GuiCapBank.java
- src/main/java/crazypants/enderio/machine/capbank/TileCapBank.java
- src/main/java/crazypants/enderio/machine/capbank/network/CapBankClientNetwork.java
- src/main/java/crazypants/enderio/machine/capbank/network/CapBankNetwork.java
- src/main/java/crazypants/enderio/machine/capbank/network/ClientNetworkManager.java
- src/main/java/crazypants/enderio/machine/capbank/network/ICapBankNetwork.java
- src/main/java/crazypants/enderio/machine/capbank/network/NetworkState.java
- src/main/java/crazypants/enderio/machine/capbank/packet/PacketNetworkEnergyResponse.java
- src/main/java/crazypants/enderio/machine/capbank/render/IoDisplay.java
- src/main/java/crazypants/enderio/power/PerTickIntAverageCalculator.java
Also got rid of the blinking colors for the info panel text
> track capbank input and output separately - display both on tall info panels

- src/main/java/crazypants/enderio/machine/painter/PainterUtil.java
Simple null check, may fix #2007. And if not---it's harmless...
> Added check for blocks without item

- src/main/java/crazypants/enderio/item/ToolTickHandler.java
* Mouse wheel data is no longer consumed; fixes #2049
* Mouse wheel handling now uses Forge mouse event
> Fix Mouse Wheel Handling

- src/main/java/crazypants/enderio/machine/vat/BlockVat.java
* Added amount check when filling items on right click, fixes #2061
* Also added missing sneaking check
> Fix: Added VAT amount check

- src/main/java/crazypants/enderio/machine/crafter/TileCrafter.java
* Fixes #2038. Recipes that return different amounts based on input item
NBT or phase of the moon will result in the correct amount now.
* Fix for the same case: Result itemstacks will never be too big.
* Fix: Recipes that return different NBT data based upon input item NBT
or phase of the moon will be handled (nearly) correctly. Remaining error
is that there will be an output queue instead of the crafting being
paused. Not worth to fix.
* Fix: Overflow items are now merged into the result stack correctly.
* Improvement: Container items should now be handled correctly no matter
what kind of funny things a mod does with its items.
> Fixes for the Crafter

- src/main/java/crazypants/enderio/block/BlockDarkSteelPressurePlate.java
- src/main/java/crazypants/enderio/block/BlockItemDarkSteelPressurePlate.java
* Silent dark pressure plate no longer drops normal dark pressure plate
* NEI now can hand out silent dark pressure plates
> Fix: Dark Pressure Plate item now works as intended

- src/api/java/baubles/api/BaubleType.java
- src/api/java/baubles/api/BaublesApi.java
- src/api/java/baubles/api/IBauble.java
- src/api/java/baubles/api/package-info.java
- src/main/java/crazypants/enderio/enchantment/EnchantmentSoulBound.java
- src/main/java/crazypants/enderio/tool/BaublesTool.java
* Includes Baubles API 1.0.1.10 (will not be included in ender io jar)
* Fixes #2074
> Added Soulbound support for Baubles

- resources/assets/enderio/lang/en_US.lang
- src/main/java/crazypants/enderio/item/KeyTracker.java
- src/main/java/crazypants/enderio/item/MagnetController.java
- src/main/java/crazypants/enderio/item/PacketMagnetState.java
> KeyBinding for the Magnet

- src/main/java/crazypants/enderio/machine/farm/TileFarmStation.java
> Fixed Farming Station power use and display

- src/main/java/crazypants/enderio/machine/farm/Fertilizer.java
- src/main/java/crazypants/enderio/machine/farm/TileFarmStation.java
Currently supported:
* Vanilla Bone Meal
* Forestry Fertilizer
> Generic fertilizer support for Farming Station

- src/main/java/crazypants/enderio/teleport/telepad/BlockTelePad.java
- src/main/java/crazypants/enderio/teleport/telepad/PacketUpdateCoords.java
- src/main/java/crazypants/enderio/teleport/telepad/TileTelePad.java
Now coordinate changes are properly sent to other clients.
> Properly synchronized Telepad coordinate changes

- src/main/java/crazypants/enderio/machine/farm/Fertilizer.java
- src/main/java/crazypants/enderio/machine/farm/TileFarmStation.java
Now supported:
* Vanilla Bonemeal
* Forestry FertilizerCompound
* Botania FloralFertilizer (no harvest yet)
* Metallurgy Fertilizer
* GardenCore Compost_pile
> Support for more types of fertilizer

- src/main/java/crazypants/enderio/machine/farm/FarmersRegistry.java
- src/main/java/crazypants/enderio/machine/farm/farmers/FlowerPicker.java
* Farming station will now pick flowers (not plant!)
* Supported flowers: Vanilla single block, BoP, Botany, Botania
> Added flower support to farming station

- resources/assets/enderio/lang/fr_FR.lang
- Added the missing item/conduits/machine/blocks/powders/etc...
- Corrected some mis-translations
- This is still a work in progress, I'll address the rest in a next update as soon as I can
> Added missing translation + minor corrections

- resources/assets/enderio/lang/fr_FR.lang
Additional translations done and/or added
> Added missing translations (part2)

- src/main/java/crazypants/enderio/machine/farm/TileFarmStation.java
Some mods *do check the item in hand...
> Properly set up farmerJoe when fertilizing

- resources/assets/enderio/lang/en_US.lang
- src/main/java/crazypants/enderio/item/ItemMagnet.java
- src/main/java/crazypants/enderio/item/MagnetController.java
- src/main/java/crazypants/enderio/machine/wireless/WirelessChargerController.java
- src/main/java/crazypants/enderio/tool/BaublesTool.java
- src/main/java/crazypants/enderio/tool/BaublesToolwithBaubles.java
* Wireless Charger charges Baubles items
* Fix: No more log spam without Baubles installed
* EIO Magnet now can be worn as amulet (Magnet must be enabled first)
> More Baubles support

- src/main/java/crazypants/enderio/machine/farm/farmers/PlantableFarmer.java
* Tested with Witchery's Water Artichoke
* Will not pick up vanilla's Water Lily by accident
* re #2221
> Support water plants in farming station

- src/main/java/crazypants/enderio/machine/tank/BlockTank.java
- src/main/java/crazypants/enderio/machine/tank/TileTank.java
- src/main/java/crazypants/enderio/machine/vat/BlockVat.java
- src/main/java/crazypants/enderio/machine/vat/TileVat.java
- src/main/java/crazypants/util/FluidUtil.java
- src/main/java/crazypants/util/ITankAccess.java
re #2061 and same reported for tank in irc
> Unify code to fill buckets

- src/main/java/crazypants/util/ItemUtil.java
Logic is the same as my last implementation, it is just heavily
optimized. As it may be called many times per tick in big networks doing
that looked appropriate.
Note: One of the optimizations relies on the fact that the code only
runs single-threaded in the server thread.
> Optimizations for doInsertItem()

- src/main/java/crazypants/enderio/machine/spawner/BlockPoweredSpawner.java
> Spawners get nasty when broken

- resources/assets/enderio/lang/en_US.lang
- src/main/java/crazypants/enderio/machine/UpgradeCapBankRecipe.java
- src/main/java/crazypants/enderio/machine/capbank/BlockCapBank.java
...also show how many items they contains in the tooltip
> #2269 don't allow upgrading capbanks when they have items in their inventory

- src/main/java/crazypants/enderio/item/ItemMagnet.java
> Be Optional on the Baubles API, not module

- src/main/java/crazypants/enderio/material/Material.java
- src/main/java/crazypants/enderio/material/MaterialRecipes.java
Cleaned up outdated code and used GameRegistry instead. Also fixed a
small spelling error.
> Recipe cleanup

- src/main/java/crazypants/enderio/item/darksteel/ItemDarkSteelAxe.java
- src/main/java/crazypants/enderio/machine/spawner/BlockPoweredSpawner.java
* Changed powered spawner to use blockHarvestEvent to insert "broken
spawner" into drops list instead of dropping it into the world
* Changed dark steel axe to use direct callback instead of global event
> Event optimizations

- resources/assets/enderio/lang/fr_FR.lang
Added missing french translations
Corrected some little mistake
Standardized translation so that everything is coherent
> Added missing translations (final)

- src/main/java/crazypants/enderio/config/Config.java
- src/main/java/crazypants/enderio/item/MagnetController.java
* By default it blacklists AE2's crystal seeds, Botania's livingrock and
Mana Tablet
> New Config: Blacklist items from Magnet

- resources/assets/enderio/config/SAGMillRecipes_Core.xml
Sag Mill Aluminum oredict support
> Aluminum Support

- resources/assets/enderio/config/SAGMillRecipes_Core.xml
To maintain internal consistency, the certus quartz recipes are adjusted
to conform to the Nether Quartz recipes.
> Conforms Certus Quartz

- src/main/java/crazypants/enderio/BlockEio.java
- src/main/java/crazypants/enderio/config/Config.java
- src/main/java/crazypants/enderio/machine/generator/combustion/BlockCombustionGenerator.java
- src/main/java/crazypants/enderio/machine/generator/combustion/TileCombustionGenerator.java
- src/main/java/crazypants/enderio/machine/generator/zombie/BlockZombieGenerator.java
- src/main/java/crazypants/enderio/machine/generator/zombie/TileZombieGenerator.java
- src/main/java/crazypants/enderio/machine/killera/BlockKillerJoe.java
- src/main/java/crazypants/enderio/machine/killera/TileKillerJoe.java
- src/main/java/crazypants/enderio/machine/obelisk/xp/ItemXpTransfer.java
- src/main/java/crazypants/enderio/machine/obelisk/xp/TileExperienceOblisk.java
- src/main/java/crazypants/enderio/machine/reservoir/BlockReservoir.java
- src/main/java/crazypants/enderio/machine/reservoir/TileReservoir.java
- src/main/java/crazypants/enderio/machine/soul/BlockSoulBinder.java
- src/main/java/crazypants/enderio/machine/soul/TileSoulBinder.java
- src/main/java/crazypants/enderio/machine/tank/BlockTank.java
- src/main/java/crazypants/enderio/machine/tank/TileTank.java
- src/main/java/crazypants/enderio/machine/vat/BlockVat.java
- src/main/java/crazypants/enderio/machine/vat/TileVat.java
- src/main/java/crazypants/enderio/xp/ExperienceContainer.java
- src/main/java/crazypants/enderio/xp/XpUtil.java
- src/main/java/crazypants/util/FluidUtil.java
- src/main/java/crazypants/util/ITankAccess.java
* New: Emptying buckets
* Fix: Fixed many bugs, including some item-loss types
* Full IN+OUT: Tank, Reservoir, XP Obelisk, Soul Binder
* IN for input liquid, OUT for output liquid: Vat
* IN for fuel, OUT fro XP: KillerJoe
* IN for fuel: Zombie Generator
* IN for fuel/coolant: Combustion Generator
* re #1913
> Unify code to fill/empty buckets, Part 2

- src/main/java/crazypants/enderio/gui/ColorButton.java
- src/main/java/crazypants/enderio/gui/IconButtonEIO.java
- src/main/java/crazypants/enderio/gui/RedstoneModeButton.java
- src/main/java/crazypants/gui/GuiContainerBase.java
should no longer ignore clicks or cause the impression of lag
> better implementation for right clicking on buttons

- src/main/java/crazypants/enderio/item/KeyTracker.java
* Hotbar: Not harmful, but would be replaced by the server anyway
* Baubles: Harmful, as Baubles seems to syncs from client to server
* re #2313
> Fix: Magnet keyBinding undoing its own work

- src/main/java/crazypants/enderio/gui/VScrollbarEIO.java
> enable blend mode and push enable bit as done by IconButtonEIO

- src/main/java/crazypants/enderio/material/BlockFusedQuartz.java
- src/main/java/crazypants/enderio/material/FusedQuartzRenderer.java
* Don't crash on invalid block meta value
* re #2333
> Clamp meta in glass renderer

- resources/assets/enderio/lang/en_US.lang
- src/main/java/crazypants/enderio/config/Config.java
- src/main/java/crazypants/enderio/teleport/TravelController.java
- src/main/java/crazypants/enderio/teleport/anchor/TileTravelAnchor.java
Solves the "issue" in #2296 where jump enhancements/flight can cause difficulties in activating travel anchors and/or cause increased iteration periods between attempts.
> Elevator functionality and sneak activation

- src/main/java/crazypants/enderio/machine/AbstractPoweredTaskEntity.java
Also removed a 2nd call to currentTask.getCompletedResult()
> #2345 remember the random chance value when the recipe couldn't be started

- src/main/java/crazypants/enderio/machine/spawner/TilePoweredSpawner.java
may be a solution for #2373, unless matching the creature to the type of liquid is needed...
> Spawn water creatures in liquid

- src/main/java/crazypants/enderio/machine/obelisk/ObeliskSpecialRenderer.java
> Use client tick in render animation

- src/main/java/crazypants/enderio/BlockEio.java
- src/main/java/crazypants/enderio/machine/reservoir/BlockReservoir.java
* Restored Reservoir special multi-block handling (thx git)
* Restored sneaking behavior
* re #2309
> Fix: Bucket Handling

- src/main/java/crazypants/enderio/config/Config.java
- src/main/java/crazypants/enderio/item/ItemMagnet.java
- src/main/java/crazypants/enderio/item/KeyTracker.java
- src/main/java/crazypants/enderio/item/MagnetController.java
* Config values re #2387 (defaults unchanged)
* Fix to @Optional.Method annotation might help with #2414 #2246
> More Config for Magnet

- src/main/java/crazypants/enderio/machine/gui/AbstractMachineContainer.java
* Fixes mixup of TE slots and GUI slots
* Fixes off-by-one erro with hotbar
* re #2410
> Fix: Shift-Click handling

- resources/assets/enderio/lang/en_US.lang
- src/main/java/crazypants/enderio/machine/invpanel/BlockInventoryPanel.java
- src/main/java/crazypants/enderio/machine/invpanel/BlockItemInventoryPanel.java
- src/main/java/crazypants/enderio/machine/invpanel/GuiInventoryPanel.java
- src/main/java/crazypants/enderio/machine/invpanel/PacketGuiSettings.java
- src/main/java/crazypants/enderio/machine/invpanel/TileInventoryPanel.java
- src/main/java/crazypants/gui/GuiContainerBase.java
based on feedback from Chaoschunk
> Invpanel improvements

- resources/assets/enderio/config/SAGMillRecipes_Core.xml
Expanding on #2243, barley can now be SAG milled into flour.
> Add Natura Barley to Flour SAG Mill recipe.

- src/main/java/crazypants/enderio/EnderIO.java
- src/main/java/crazypants/enderio/tool/EnderIOCrashCallable.java
Also stop early when AE2 rv1 is loaded
> Add our take on unsupported mods to the crash report

- src/main/java/crazypants/enderio/machine/invpanel/InventoryPanelContainer.java
Shift clicking items is done using Conatiner.transferStackinSlot - but this method is executed on both sides (client & server). If the server had a different view of the slot contents it will make a different decision on the server as on the client. This looks like a dupe but the items displayed on the client side are actually ghost items.
This is a bug present in all vanilla containers when items are extracted/inserted (using eg item conduits) concurrent to the shift clicking in the GUI.
As the inventory panel's return area is a major element of that machine and the item conduits in use typically have many speed upgrades installed this issue occurs very easily esp on servers.
As a work around send the content of the return area to all players after transferStackInSlot has been active on …
> try to combat Minecraft's transferStackInSlot desync issue

- resources/assets/enderio/config/AlloySmelterRecipes_Core.xml
- resources/assets/enderio/config/AlloySmelterRecipes_User.xml
- resources/assets/enderio/config/SAGMillRecipes_Core.xml
- resources/assets/enderio/config/SAGMillRecipes_User.xml
- src/main/java/crazypants/enderio/machine/crusher/CrusherRecipeManager.java
I have made the SAGMill xml a little easier to read and a bit of cleanup.
> Fixed spelling, some grammar, and a lot of formatting

- src/main/java/crazypants/enderio/machine/crafter/ContainerCrafter.java
- src/main/java/crazypants/enderio/machine/crafter/DummyCraftingGrid.java
- src/main/java/crazypants/enderio/machine/crafter/TileCrafter.java
And while at it - allow the use of tools with damage value in crafting (eg AE2 quartz cutting knife)
> #2552 prevent endless loops in crafting

- resources/assets/enderio/config/AlloySmelterRecipes_Core.xml
- resources/assets/enderio/config/AlloySmelterRecipes_User.xml
- resources/assets/enderio/config/EnchanterRecipes_Core.xml
- resources/assets/enderio/config/EnchanterRecipes_User.xml
- resources/assets/enderio/config/OreDictionaryPreferences_Core.xml
- resources/assets/enderio/config/OreDictionaryPreferences_User.xml
- resources/assets/enderio/config/PainterPaintSources_Core.xml
- resources/assets/enderio/config/PainterPaintSources_User.xml
- resources/assets/enderio/config/PoweredSpawnerConfig_Core.json
- resources/assets/enderio/config/PoweredSpawnerConfig_User.json
- resources/assets/enderio/config/SAGMillRecipes_Core.xml
- resources/assets/enderio/config/SAGMillRecipes_User.xml
- resources/assets/enderio/config/SliceAndSpliceRecipes_Core.xml
- resources/assets/enderio/config/VatRecipes_Core.xml
- resources/assets/enderio/config/VatRecipes_User.xml
Finishing up all files and fixed a few missed items in others.
> A bit more cleanup, formatting, and consistency in XMLs.

- src/main/java/crazypants/enderio/machine/farm/FarmersRegistry.java
also compile the patterns just once
> #2579 protect against blocks without a registered name

- src/main/java/crazypants/enderio/ClientProxy.java
- src/main/java/crazypants/enderio/TileEntityEio.java
- src/main/java/crazypants/enderio/machine/AbstractMachineBlock.java
- src/main/java/crazypants/enderio/machine/TechneMachineRenderer.java
- src/main/java/crazypants/enderio/teleport/telepad/TelePadRenderer.java
- src/main/java/crazypants/enderio/teleport/telepad/TelePadSpecialRenderer.java
- src/main/java/crazypants/render/TechneModelRenderer.java
- src/main/java/crazypants/render/TechneUtil.java
* Fixes problem with texture sizes (Forge bug)
* Implements a framework that allows easy rendering of only parts of
models.
* Changes telepad to use that.
> Techne Rendering

- resources/assets/enderio/lang/es_ES.lang
Up-to-date Spanish translation, ready to add to the main files.
> Spanish translation

- README.md
> #2532 Fix some spelling in README.md

- resources/assets/enderio/config/SAGMillRecipes_Core.xml
Added TE/TF ingots/blocks. Closes #1714
Finished Nether Ores support. Closes #182
> #1714 #182 More SAG Mill recipes

- src/main/java/crazypants/enderio/machine/MachineRecipes.java
- src/main/java/crazypants/enderio/material/MaterialRecipes.java
- src/main/java/crazypants/enderio/teleport/TeleportRecipes.java
> Ore Dictionary support for recipes

- src/main/java/crazypants/enderio/conduit/redstone/RedstoneConduitNetwork.java
Huge thanks to HenryLoenwind for basically fixing the bug once I located where it was happening!
> Fix for #2740 - redstone conduits don't cause block updates

- src/main/java/crazypants/enderio/tool/EnderIOCrashCallable.java
* Re-added AE2 rv1; it can be pulled in by other mods than AE2
* Added old RF API; e.g. via Buildcraft
* Added source of the bad APIs to the message
* Fixed conditional plural wording in messages
* re #2786
> More reporting on old APIs on crashes

- src/main/java/crazypants/enderio/conduit/BlockConduitBundle.java
> Ability to replace facades

- src/main/java/crazypants/enderio/machine/AbstractPoweredTaskEntity.java
- src/main/java/crazypants/enderio/machine/PoweredTask.java
getCompoundTag() never returns null, it returns a new empty object
instead
> Logic fix for reading the current task from nbt

- src/main/java/crazypants/enderio/conduit/gui/item/ItemSettings.java
- src/main/java/crazypants/enderio/conduit/item/filter/ExistingItemFilter.java
- src/main/java/crazypants/enderio/conduit/item/filter/IItemFilter.java
- src/main/java/crazypants/enderio/conduit/item/filter/ItemFilter.java
- src/main/java/crazypants/enderio/conduit/item/filter/ModItemFilter.java
- src/main/java/crazypants/enderio/conduit/item/filter/PowerItemFilter.java
Now its possible for other mods to create filters for conduits without the need to change the enderio code, by implementing the IItemFilter interface.
> changed getGui method for conduit filters

- src/main/java/crazypants/enderio/teleport/telepad/TelePadSpecialRenderer.java
* re #2832
* It makes no sense for this to be null, but a defensive null check here
is basically free.
> Added some defensive null checking

- src/main/java/crazypants/enderio/conduit/item/filter/ExistingItemFilter.java
- src/main/java/crazypants/enderio/conduit/item/filter/IItemFilter.java
- src/main/java/crazypants/enderio/conduit/item/filter/ItemFilter.java
- src/main/java/crazypants/enderio/conduit/item/filter/ModItemFilter.java
- src/main/java/crazypants/enderio/conduit/item/filter/PowerItemFilter.java
> Fix client-side code being needed on the server

- src/main/java/crazypants/enderio/tool/EnderIOCrashCallable.java
> More checks on unsupported software on crash

- src/main/java/crazypants/enderio/item/MagnetController.java
- src/main/java/crazypants/util/BotaniaUtil.java
> Solegnolia support for Magnet

- src/main/java/crazypants/enderio/item/darksteel/DarkSteelController.java
- src/main/java/crazypants/enderio/item/darksteel/PacketUpgradeState.java
> Don't crash if in MP a client doesn't have another player's profile loaded

- src/main/java/crazypants/enderio/ClientProxy.java
- src/main/java/crazypants/enderio/conduit/liquid/LiquidConduitRenderer.java
I grabbed a random "TODO". Even though this calc is not done every
frame, this still saves some time.
> Cache some rendering calcs

- src/main/java/crazypants/enderio/machine/alloy/VanillaSmeltingRecipe.java
- src/main/java/crazypants/enderio/material/OreDictionaryPreferences.java
* re #2828 (may be a fix, or may be an unrelated mistake)
> Keep care not to store ItemStacks of furnace recipes

- src/main/java/crazypants/enderio/machine/tank/TileTank.java
> Fix: NPE on kamikaze fluid container

- resources/assets/enderio/config/EnchanterRecipes_Core.xml
> #1712 #880 More enchants for enchanter

- src/main/java/crazypants/enderio/machine/buffer/BlockBuffer.java
- src/main/java/crazypants/enderio/machine/painter/BlockPaintedGlowstone.java
- src/main/java/crazypants/enderio/teleport/anchor/BlockTravelAnchor.java
- src/main/java/crazypants/enderio/teleport/anchor/TileTravelAnchor.java
- src/main/java/crazypants/enderio/waila/WailaCompat.java
> Fix unpainted blocks being unexpectedly unpainted

- build.gradle
- gradle.properties
- src/main/java/crazypants/enderio/EnderIO.java
- src/main/java/crazypants/enderio/machine/recipe/BasicManyToOneRecipe.java
- src/main/java/crazypants/enderio/machine/vat/VatRecipe.java
- src/main/java/crazypants/enderio/material/MaterialRecipes.java
- src/main/java/crazypants/enderio/material/PowderIngot.java
- src/main/java/crazypants/util/EE3Util.java
* Added EE3 EMC values
* Fixed reversed ender pearl dust registration logic
* re #2817
> EE3 EMC values

- src/main/java/crazypants/enderio/conduit/power/NetworkPowerManager.java
Also reduce log spam, this error happens in tight loops.
re #2804
> Add additional error information to logfile

- eclipseFormat.xml
Also enable the "formatter:off/on" command comments
> Change code style to put enum declarations on their own lines

- src/main/java/crazypants/enderio/machine/light/TileElectricLight.java
> Switch on lights when they get power

- src/main/java/crazypants/util/ShadowInventory.java
> Use our Utils, not CCC's

- src/main/java/crazypants/enderio/item/darksteel/DarkSteelController.java
> Don't skip night vision processing while flying

- src/main/java/crazypants/enderio/machine/invpanel/InventoryPanelContainer.java
> Ignore request to craft half a result in InvPanel

- src/main/java/crazypants/enderio/enchantment/EnchantmentSoulBound.java
* Ignore cancelled events
* Don't trash items if the inventory is full
* Don't dupe items if another mod works on the PlayerEvent.Clone, too
* Lookup Soulbound enchantment more streightforward
* re #2980
* re comment on 3b11ccc1e0f525401e51d538e26a7b33f343070f
> Some fixes for Soulbound

- src/main/java/crazypants/enderio/machine/light/TileElectricLight.java
> Switch on lights when they get wireless power, too

- src/main/java/crazypants/enderio/machine/gui/AbstractMachineContainer.java
- src/main/java/crazypants/enderio/machine/gui/GuiMachineBase.java
followup to #2411. This time really take the index into the inventory, not the slot list.
Also renamed the parameters to have a consistent naming.
> Fix: Shift-Click handling, second try

- src/main/java/crazypants/enderio/conduit/me/MEConduit.java
> Fix for limiting ME conduit connection modes

- src/main/java/crazypants/enderio/teleport/anchor/BlockTravelAnchor.java
> Dont't crash with paintable block being painted as travel anchor

- src/main/java/crazypants/enderio/config/Config.java
> Add some more Hoes to Farming Station whitelist

- src/main/java/crazypants/enderio/conduit/AbstractConduit.java
- src/main/java/crazypants/enderio/conduit/ConduitUtil.java
- src/main/java/crazypants/enderio/conduit/IConduit.java
> Updated createNetworkForType() based on comments from #2944

- resources/assets/enderio/config/SAGMillRecipes_Core.xml
> SAG Mill recipe for lapis to lapis dust (IC2)

- resources/assets/enderio/lang/en_US.lang
- src/main/java/crazypants/enderio/machine/monitor/GuiPowerMonitor.java
> Display helpful text in unconnected power monitor

- src/main/java/crazypants/enderio/machine/obelisk/ObeliskRenderer.java
- src/main/java/crazypants/enderio/machine/obelisk/ObeliskSpecialRenderer.java
and make sure we have the right OpenGL bits set when rendering as item. This should also fix some older rendering issues with the floating item transparency.
re #3024
> Cleanup obelisk rendering even more

- src/main/java/crazypants/enderio/machine/painter/BlockPaintedFenceGate.java
There is no such  thing a a nether brick fence gate
re #3031
> Removed stray fence gate from recipe

- src/main/java/crazypants/enderio/machine/FakePlayerEIO.java
- src/main/java/crazypants/enderio/machine/farm/FakeFarmPlayer.java
- src/main/java/crazypants/enderio/machine/farm/FakeNetHandlerPlayServer.java
re #2983, #2957, #2575, MinecraftForge/MinecraftForge#1948
> Make FakePlayer more life-like

- src/main/java/crazypants/enderio/conduit/gui/item/ExistingItemFilterGui.java
- src/main/java/crazypants/enderio/conduit/gui/item/PacketExistingItemFilterSnapshot.java
- src/main/java/crazypants/enderio/conduit/item/filter/ExistingItemFilter.java
> Added blacklist feature to the existing item filter

- src/main/java/crazypants/enderio/gui/GuiContainerBaseEIO.java
- src/main/java/crazypants/enderio/nei/EnchanterRecipeHandler.java
- src/main/java/crazypants/enderio/nei/SliceAndSpliceRecipeHandler.java
- src/main/java/crazypants/enderio/nei/SoulBinderRecipeHandler.java
- src/main/java/crazypants/enderio/nei/VatRecipeHandler.java
> Fix missed GUI textures in NEI handlers

- src/main/java/crazypants/enderio/conduit/gui/LiquidSettings.java
- src/main/java/crazypants/enderio/conduit/liquid/FluidFilter.java
> Honor NBT in fluid filter, fix fluid filter fluid render

- src/main/java/crazypants/enderio/machine/recipe/RecipeConfig.java
> Don't crash on missing recipe group name

- src/main/java/crazypants/enderio/api/teleport/TravelSource.java
- src/main/java/crazypants/enderio/teleport/TravelController.java
- src/main/java/crazypants/enderio/teleport/anchor/TravelEntitySpecialRenderer.java
> Fix configurability of travel sources

- src/main/java/crazypants/enderio/machine/vat/GuiVat.java
- src/main/java/crazypants/enderio/machine/vat/VatRecipe.java
- src/main/java/crazypants/enderio/machine/vat/VatRecipeManager.java
- src/main/java/crazypants/util/EE3Util.java
* Fix: Input fluid amount in now checked
* Gui will display multipliers for incomplete recipes
* Less black magic
* re #2878
> Vat Recipe overhaul

- src/main/java/crazypants/enderio/item/KeyTracker.java
> Fix for magnet hotkey trying to toggle the wrong item

- src/main/java/crazypants/enderio/machine/farm/FakeNetHandlerPlayServer.java
> Prevent outright crash when used on a kcauldron server

- src/main/java/crazypants/enderio/machine/soul/TileSoulBinder.java
by checking required XP in drain()/fill() as it does in push()/pull()
> Prevent Soul Binder from moving around liquid needlessly

- src/main/java/crazypants/enderio/BlockEio.java
Adds a check for canUse for tools which might relay on power or other reasons why a tool should not be used
> Add ITool.canUse check

- src/main/java/crazypants/enderio/enchantment/EnchantmentSoulBound.java
- src/main/java/crazypants/util/GalacticraftUtil.java
> Add support for soulbound items in a Galacticraft inventory

- src/main/java/crazypants/enderio/config/Config.java
- src/main/java/crazypants/enderio/machine/farm/TileFarmStation.java
People have been complaining about the lack of configurability for the "incredibly short" range of it. https://www.reddit.com/r/feedthebeast/comments/3xkr7v/whats_with_the_lack_of_good_nonmfr_farming_mods/
head->table, but a tiny bit of truth was hidden in that statement.
> Added config option for farm size

- src/main/java/crazypants/enderio/item/darksteel/ItemDarkSteelShears.java
* Distance sorting for harvested blocks was non-functional
* Dark Steel enchantability was missing
> Fixes for shears

- src/main/java/crazypants/enderio/config/Config.java
- src/main/java/crazypants/enderio/machine/killera/TileKillerJoe.java
Default: Killer Joe swings but nothing happens
Option 1: Killer Joe ignores the player
Option 2: Killer Joe ignores the no-PvP rule
> Add options for Killer Joe on a non-PvP server

- src/main/java/crazypants/enderio/conduit/gui/item/ModItemFilterGui.java
- src/main/java/crazypants/enderio/conduit/gui/item/PacketModItemFilter.java
- src/main/java/crazypants/enderio/conduit/item/filter/ModItemFilter.java
I'm not sure about the button placement in the GUI. Any ideas?
re #2936
> Added blacklist feature to the mod item filter

- src/main/java/crazypants/enderio/machine/generator/stirling/GuiStirlingGenerator.java
> Nice number formatting for stirling generator GUI

- resources/assets/enderio/config/VatRecipes_Core.xml
> Tag Nutrient Distilation as having optional inputs

- resources/assets/enderio/config/AlloySmelterRecipes_Core.xml
- resources/assets/enderio/config/OreDictionaryPreferences_Core.xml
- resources/assets/enderio/config/SAGMillRecipes_Core.xml
- src/main/java/crazypants/enderio/config/Config.java
> Removed outdated config setting

- src/api/java/dan200/computercraft/api/ComputerCraftAPI.java
- src/api/java/dan200/computercraft/api/filesystem/package-info.java
- src/api/java/dan200/computercraft/api/lua/package-info.java
- src/api/java/dan200/computercraft/api/media/package-info.java
- src/api/java/dan200/computercraft/api/package-info.java
- src/api/java/dan200/computercraft/api/peripheral/package-info.java
- src/api/java/dan200/computercraft/api/permissions/package-info.java
- src/api/java/dan200/computercraft/api/redstone/package-info.java
- src/api/java/dan200/computercraft/api/turtle/package-info.java
- src/main/java/crazypants/enderio/EnderIO.java
- src/main/java/crazypants/enderio/conduit/redstone/RedstoneConduit.java
> Fixed ComputerCraft integration.

- src/main/java/crazypants/enderio/conduit/gui/GuiExternalConnectionSelector.java
Implemens #1984 
See #3287 for 1.7.10 PR.
> Show Block Name in GuiExternalConnectionSelector in 1.8.9. 

- src/main/java/crazypants/enderio/power/PowerDistributor.java
> Fixed PowerDistributor distributing power backwards

- src/main/java/crazypants/enderio/teleport/TravelController.java
> Side-hardened IMC processing

- src/main/java/crazypants/enderio/config/Config.java
> Added new Magic Crops hoe names

- src/main/java/crazypants/enderio/item/ItemMagnet.java
- src/main/java/crazypants/enderio/machine/capbank/ContainerCapBank.java
- src/main/java/crazypants/util/BaublesUtil.java
> Handle Baubles inv more careful in MP

- src/main/java/crazypants/enderio/config/Config.java
- src/main/java/crazypants/enderio/teleport/telepad/TileTelePad.java
Now size of energy buffer and energy input are configurable.
Closes #3306
> Added config options for TelePad

- resources/assets/enderio/lang/zh_CN.lang
> Update zh_CN.lang and add missing localization strings.

- src/main/java/crazypants/enderio/machine/farm/FarmersRegistry.java
- src/main/java/crazypants/enderio/machine/farm/farmers/ForestryFarmer.java
Added support for planting forestry saplings to farming station. Harvesting was already working using the existing code so i didn't touch that.
> Added forestry sapling support to farm station

- build.gradle
- gradle.properties
- resources/assets/enderio/config/recipe_items_core.xml
- resources/assets/enderio/models/item/itemMeConduit.json
- resources/assets/enderio/models/item/itemMeConduitDense.json
- src/main/java/crazypants/enderio/ModObject.java
- src/main/java/crazypants/enderio/conduit/AbstractConduit.java
- src/main/java/crazypants/enderio/conduit/IConduitBundle.java
- src/main/java/crazypants/enderio/conduit/TileConduitBundle.java
- src/main/java/crazypants/enderio/conduit/me/IMEConduit.java
- src/main/java/crazypants/enderio/conduit/me/ItemMEConduit.java
- src/main/java/crazypants/enderio/conduit/me/MEConduit.java
- src/main/java/crazypants/enderio/conduit/me/MEConduitGrid.java
- src/main/java/crazypants/enderio/conduit/me/MEConduitNetwork.java
- src/main/java/crazypants/enderio/conduit/me/MEUtil.java
- src/main/java/crazypants/enderio/conduit/render/ConduitBundleRenderManager.java
Just port of ME conduits from `master` and adopt to 1.10.
> Port ME conduits to 1.10

- resources/assets/enderio/config/SAGMillRecipes_Core.xml
Changed to ore dictionary entries where available, as well as new item
ids.
> Fix for Applied Energistics 2 SAG Mill Recipes

- resources/assets/enderio/config/AlloySmelterRecipes_Core.xml
Fixed recipes requiring ThermalFoundation Pyrothium (for 1.10.2)
> Fixed recipes requiring ThermalFoundation Pyrothium (for 1.10.2)

- resources/assets/enderio/config/AlloySmelterRecipes_Core.xml
Change from ModID to ore dictionary
> Change from ModID to ore dictionary (Pyrothium, 1.10)

- src/main/java/crazypants/enderio/conduit/EnderIOConduits.java
- src/main/java/crazypants/enderio/conduit/init/ConduitObject.java
Created and Conduit Object and EnderIOConduits file based off the -machines equivalents
> Conduit Ground Works

- src/main/java/crazypants/enderio/base/conduit/ConduitUtil.java
- src/main/java/crazypants/enderio/base/conduit/IConduit.java
- src/main/java/crazypants/enderio/base/conduit/IConduitNetwork.java
Added Conduit Network validity checking using IConduitNetwork instead of objects from -conduits.
Filled out IConduitNetwork interface for future use
> Conduit Networks and Other Conduit Utils

- src/main/java/crazypants/enderio/base/recipe/Recipe.java
Henry's patch extended with check for shapeless (item based) recipes
> Fix isInputForRecipe for recipes have the same itemtype multiple times

- resources/assets/enderio/lang/en_us.lang
Added names for all the creative tabs and fixed the names for the filters.
> Added/Fixed Names

- build.gradle
- enderio-base/enderio-base.gradle
- enderio-base/src/main/java/crazypants/enderio/base/EnderIO.java
- enderio-conduits/enderio-conduits.gradle
- enderio-invpanel/enderio-invpanel.gradle
- enderio-machines/enderio-machines.gradle
- enderio-machines/src/main/java/crazypants/enderio/machines/EnderIOMachines.java
- gradle.properties
- settings.gradle
Added the following:
* Mod dependencies string replacement in source
* Jar signing
* Fixed version string: [apex+build] -> [apex.build]
> Build file update and cleanup

- build.gradle
- enderio-base/gradle.properties
- enderio-conduits/gradle.properties
- enderio-invpanel/gradle.properties
- enderio-machines/gradle.properties
- settings.gradle
We can now exclude projects from a build but they still show up in
eclipse.
Filed mod depencencies duplication.
> Updated build system to support excluded projects

- .gitignore
- build.gradle
- doc/changelog.html
- enderio-base/gradle.properties
- enderio-conduits/gradle.properties
- enderio-invpanel/gradle.properties
- enderio-machines/gradle.properties
* The build file now successfuly produce a fully reobfuscated 'all' jar.
* Reorganized the build file.
* Reworked the version scheme.
* Moved the HTML for the changelog into a file.
* Added module name for all modules.
> Fixed build reobfuscation and general cleanup

- enderio-machines/src/main/java/crazypants/enderio/machines/machine/teleport/anchor/TileTravelAnchor.java
> Fixed travel anchor owner

- enderio-machines/src/main/java/crazypants/enderio/machines/machine/generator/stirling/GuiStirlingGenerator.java
- enderio-machines/src/main/resources/assets/enderio/lang/en_us.lang
moving away from RF... also renamed some local variables in the code.
> Fix power unit in Stirling Generators' progress tooltip

- enderio-base/src/main/java/crazypants/enderio/base/conduit/ConduitUtil.java
- enderio-conduits/src/main/java/crazypants/enderio/conduit/BlockConduitBundle.java
- enderio-conduits/src/main/java/crazypants/enderio/conduit/packet/PacketOpenConduitUI.java
- enderio-conduits/src/main/java/crazypants/enderio/conduit/power/PowerConduit.java
Could be further optimised later to use only the ordinal integer
> Conduits Fixes

- enderio-base/src/main/resources/assets/enderio/config/recipes/materials.xml
Henry Please Accept #4496 First or this will break
@EpicSquid <3 Your turn
> Add All The Balls Recipes 

- enderio-base/src/main/resources/assets/enderio/config/recipes/balls.xml
All of these are subject to change atm, however they should be reasonably balanced
> Added ball values for new balls

- enderio-conduits/src/main/resources/assets/enderioconduits/advancements/goals/all_filters.json
The id for the Power Item Filter is item_power_item_filter and not item_powered_item_filter.
> Fixed advancement error.

- enderio-conduits/src/main/resources/assets/enderioconduits/advancements/start/1_binder_composite.json
- enderio-machines/src/main/resources/assets/enderiomachines/advancements/basics/sagmill/2_sagmill_flowers.json
- enderio-machines/src/main/resources/assets/enderiomachines/advancements/basics/sagmill/3_sagmill_bushes.json
- enderio-machines/src/main/resources/assets/enderiomachines/advancements/basics/sagmill/4_brown.json
- enderio-machines/src/main/resources/assets/enderiomachines/advancements/basics/sagmill/5_green.json
- enderio-machines/src/main/resources/assets/enderiomachines/advancements/basics/sagmill/7_black.json
- enderio-machines/src/main/resources/assets/enderiomachines/advancements/basics/sagmill/a_powder_coating.json
Fixes "Destroy Something Beautiful"
"Who Needs Squid" 
"Classic Color"
"Useful in Death"
"Caution:Do Not Eat"
"Who Needs Jungles"
"I Am Not Grout"
> FIX All advancements

- resources/assets/enderio/models/block/telepad_center.json
- resources/assets/enderio/models/block/telepad_corner.json
- resources/assets/enderio/models/block/telepad_crossbeams.json
- resources/assets/enderio/models/block/telepad_side.json
Split the telepad model into center, side, corner, and crossbeams.
> Telepad Models

- enderio-base/src/main/java/crazypants/enderio/base/config/Config.java
- enderio-base/src/main/java/crazypants/enderio/base/config/config/DarkSteelConfig.java
- enderio-base/src/main/java/crazypants/enderio/base/handler/darksteel/DarkSteelRecipeManager.java
- enderio-base/src/main/java/crazypants/enderio/base/item/darksteel/ItemDarkSteelAxe.java
- enderio-base/src/main/java/crazypants/enderio/base/item/darksteel/upgrade/hoe/HoeUpgrade.java
- enderio-base/src/main/resources/assets/enderio/lang/en_us.lang
> Hoe upgrade stuff

- enderio-machines/src/main/resources/assets/enderio/config/recipes/sagmill_ores.xml
> Reverts SleepyTrousers/EnderIO#4491

- enderio-base/src/main/resources/assets/enderio/lang/ru_ru.lang
> fix ru_ru.lang

- enderio-integration-forestry/src/main/resources/assets/enderio/lang/ru_ru.lang
This is a corrected Version of #4562
> Create Forestry ru_ru.lang

- enderio-integration-tic/src/main/resources/assets/enderio/lang/ru_ru.lang
> Create TIC ru_ru.lang

- enderio-machines/src/main/resources/assets/enderio/lang/ru_ru.lang
> Create Machines ru_ru.lang

- enderio-base/src/main/resources/assets/enderio/config/recipes/base.xml
Fix Enderio Being better at nuclearcraft recipes than nuclearcraft itself.
> Fix Enderio being better at nuclearcraft recipy

- enderio-base/src/main/resources/assets/enderio/config/recipes/base.xml
> Fix NeclearCraft recipe

- enderio-machines/src/main/resources/assets/enderio/config/recipes/sagmill_ores.xml
> Fix Thermal ores

- enderio-base/src/main/java/crazypants/enderio/base/capacitor/CapacitorHelper.java
> Fixed enhanced machine animations

- enderio-base/src/main/java/crazypants/enderio/base/integration/fuels/FuelUtil.java
added dense fuel, gaseous fuel, normal fuel, mixed heavy/light fuel, dense oil, distilled oil, heavy oil.
> Added buildcraft fuels

- enderio-base/src/main/java/crazypants/enderio/base/integration/jei/DarkSteelUpgradeRecipeCategory.java
As far as I can tell, this is a suitable fix. But, I am not familiar with Ender IO's code, so it might not be.
> Fix the NullPointerException in issue #5035

- enderio-conduits/src/main/java/crazypants/enderio/powertools/machine/capbank/network/CapBankNetwork.java
The actual bug was fixed but the symptom was not.
> Also adjust network statistics

- enderio-conduits/src/main/java/crazypants/enderio/conduits/conduit/liquid/EnderLiquidConduitNetwork.java
- enderio-conduits/src/main/java/crazypants/enderio/conduits/conduit/liquid/NetworkTank.java
> Multi-tank support for Ender Fluid conduits

- enderio-conduits-appliedenergistics/src/main/resources/assets/enderio/config/recipes/conduits-applied-energistics.xml
> Fix an issue with EIO Dense Conduits being better

- enderio-integration-forestry/src/main/resources/assets/enderio/config/recipes/darksteel_upgrades_forestry.xml
> Spellcheck henry

- enderio-invpanel/src/main/java/crazypants/enderio/invpanel/invpanel/GuiInventoryPanel.java
- enderio-invpanel/src/main/resources/assets/enderio/config/recipes/invpanel.xml
- enderio-invpanel/src/main/resources/assets/enderio/lang/en_us.lang
Some small bug fixes and enhancements
> Inventory Panel Bug fixes

- enderio-base/src/main/java/crazypants/enderio/base/integration/thaumcraft/ThaumcraftAspects.java
> Fix Typo on Log

- enderio-base/src/main/java/crazypants/enderio/base/filter/FilterRegistry.java
- enderio-base/src/main/java/crazypants/enderio/base/filter/capability/IFilterHolder.java
- enderio-base/src/main/java/crazypants/enderio/base/filter/gui/FilterGuiUtil.java
- enderio-conduits-refinedstorage/src/main/java/crazypants/enderio/conduit/refinedstorage/conduit/RefinedStorageConduit.java
- enderio-conduits-refinedstorage/src/main/java/crazypants/enderio/conduit/refinedstorage/conduit/gui/RefinedStorageSettings.java
- enderio-conduits/src/main/java/crazypants/enderio/conduits/conduit/TileConduitBundle.java
- enderio-conduits/src/main/java/crazypants/enderio/conduits/conduit/item/ItemConduit.java
- enderio-conduits/src/main/java/crazypants/enderio/conduits/conduit/liquid/EnderLiquidConduit.java
- enderio-conduits/src/main/java/crazypants/enderio/conduits/conduit/redstone/InsulatedRedstoneConduit.java
- enderio-conduits/src/main/java/crazypants/enderio/conduits/gui/ExternalConnectionContainer.java
- enderio-conduits/src/main/java/crazypants/enderio/conduits/gui/InventoryUpgrades.java
- enderio-conduits/src/main/java/crazypants/enderio/conduits/network/PacketConduitFilter.java
- enderio-conduits/src/main/java/crazypants/enderio/conduits/network/PacketEnderLiquidConduit.java
- enderio-conduits/src/main/resources/mcmod.info
This rework should fix all Redstone conduit filter bugs
> Redstone conduit filters rework
