SleepyTrousers/EnderIO

src/main/java/crazypants/enderio/config/Config.java
src/main/java/crazypants/enderio/machine/AbstractMachineEntity.java
src/main/java/crazypants/enderio/machine/capbank/TileCapBank.java
src/main/java/crazypants/enderio/machine/farm/TileFarmStation.java
src/main/java/crazypants/enderio/machine/killera/TileKillerJoe.java

for #1561, Wood is tool level 0, non-axes are -1, changed match function to reflect that
for  #1560, added line of sight with config to killer joe
added a null check for a crash I got intermittently when placing regular blocks next to a vibrant capacitor

Bunch of fixes

---

resources/assets/enderio/config/SAGMillRecipes_Core.xml

So other mods can add oreCoal, oreRedstone, oreDiamond, oreLapis or
oreQuartz and the SAGMill will understand them.

Use OreDict names for vanilla ore SAGMill Recipes

---

src/main/java/crazypants/enderio/EnderIO.java

There are mods that do send messages during PostInit, and are therefore not processed on EIO's side. This will allow those messages to be processed.

Process IMCs from mods who send them in PostInit

---

src/main/java/crazypants/enderio/gui/IconButtonEIO.java

Based on the code of ToolTipManager the bounds of a tooltip are always relative to the GUI and not absolute:
https://github.com/MatthiasMann/EnderIO/blob/28a51892234f0f735938afb66c2f37bb2690293d/src/main/java/crazypants/gui/ToolTipManager.java#L35

adjust tooltip location when moving a button - fixes #1609

---

src/main/java/crazypants/enderio/conduit/AbstractConduit.java
src/main/java/crazypants/enderio/conduit/AbstractItemConduit.java
src/main/java/crazypants/enderio/conduit/BlockConduitBundle.java
src/main/java/crazypants/enderio/conduit/ConduitUtil.java
src/main/java/crazypants/enderio/conduit/IConduit.java
src/main/java/crazypants/enderio/conduit/IConduitItem.java
src/main/java/crazypants/enderio/conduit/TileConduitBundle.java
src/main/java/crazypants/enderio/conduit/gas/ItemGasConduit.java
src/main/java/crazypants/enderio/conduit/item/ItemItemConduit.java
src/main/java/crazypants/enderio/conduit/liquid/ItemLiquidConduit.java
src/main/java/crazypants/enderio/conduit/liquid/LiquidConduit.java
src/main/java/crazypants/enderio/conduit/me/ItemMEConduit.java
src/main/java/crazypants/enderio/conduit/me/MEConduit.java
src/main/java/crazypants/enderio/conduit/power/ItemPowerConduit.java
src/main/java/crazypants/enderio/conduit/redstone/InsulatedRedstoneConduit.java
src/main/java/crazypants/enderio/conduit/redstone/ItemRedstoneConduit.java
src/main/java/crazypants/enderio/machine/capbank/network/CapBankClientNetwork.java

Reworked the implementation of ME conduits - solves the following issues:
- provides player ID to be compatible with the security stations
- allows connecting and disconnecting of ME conduits using a wrench
- prevents leaking of nodes on chunk unload
Important: requires picking up existing ME conduits and placing them again to get the connections correct

ME counduits should now behave better

---

src/main/java/crazypants/enderio/item/darksteel/ItemDarkSteelPickaxe.java

this fixes CrazyPants/EnderIO/#1648
the original way caused problems with items that relied on
player.inventory.currentItem, like cables from AE2 - they would set the
.currentItem-Stack to null when you placed the last cable, which in our
case would kill the pick.
Also, we’re now using the bult-in “can we place the item there?” logic
and can therefore remove canPlaceBlockOnRightClick.
It’s still not perfect though, because it doesn’t work with buckets…
see the source-code-comments. A possible solution would be to implement
a custom message that we send to ourself to switch back to the original
item slot, but I’ll just go with “you’re holding the bucket wrong”.

Different Item-Place-Logic

---

src/main/java/crazypants/enderio/machine/MachineRecipes.java
src/main/java/crazypants/enderio/machine/UpgradeCapBankRecipe.java

Resource cost for normal cap bank crafting:
CoalDust=8, Copper=8, Glowstone=8, GoldNugget=104, Iron=4, Redstone=33, Silicon=4
With upgrade recipe:
CoalDust=1, Copper=10, Glowstone=8, GoldNugget=112, Iron=8, Redstone=46
So a bit cheaper on coal dust and silicon - but overall a bit more expensive.

add recipe handler to upgrade basic to normal capacitor banks

---

src/main/java/crazypants/enderio/machine/solar/BlockSolarPanel.java

* Energy storage is no longer added twice to the tooltip

Fixed WAILA tooltip of photo cell

---

resources/assets/enderio/lang/de_DE.lang
resources/assets/enderio/lang/en_US.lang
src/main/java/crazypants/enderio/gui/TooltipAddera.java
src/main/java/crazypants/enderio/machine/solar/BlockItemSolarPanel.java

* Photovoltaic Cell now has a common tooltip text
* It says "Solar power" because people search NEI for "solar" not
"photovoltaic"
* Support in TooltipAddera for common tooltips of
IResourceTooltipProviders
* Fixed Advanced Photovoltaic Cell not displaying detailed tooltip text
shared with Photovoltaic Cell in Vanilla tooltip (Waila was ok)

Make Photovoltaic Cell more findable

---

src/main/java/crazypants/enderio/config/Config.java
src/main/java/crazypants/enderio/machine/spawner/BlockPoweredSpawner.java
src/main/java/crazypants/enderio/machine/spawner/TilePoweredSpawner.java

The comment mentioned 2 minutes (120*20) - but the code only used 1 minute (60*20).
This should make the powered spawner a bit more useful with blood magic scarifying ritual which deals damage slowly.

made despawn protection time configurable, set default to the intended 2 minutes

---

src/main/java/crazypants/enderio/machine/recipe/OreDictionaryRecipeInput.java

prevents ore dictionary from being modified (this solves the bug due to enchanter ore-dictionary recipes where number != 1)  ex ttCore XP boost

Deep copy ore dictionary list

---

src/main/java/crazypants/enderio/machine/crusher/CrusherRecipeManager.java

Commit 35324eaab0815158f5151bca30ec82760b7acbf1 was not quite solving #1745. The grinding balls and excludes actually have to be added to the respective lists in CrusherRecipeManager.
Also, fixed a small typo

#1745 Fix grinding ball handling

---

src/main/java/crazypants/enderio/machine/farm/TileFarmStation.java
src/main/java/crazypants/enderio/machine/farm/farmers/TreeFarmer.java

* Fix: Shears will stop shearing after being destroyed
* Optimization: Don't bother trying to do work if there is no axe or no
tree (harvestBlock() is allowed to return null...)
* Optimization: Changed hasAxe handling to the same as hasShears (if we
have an axe we'll keep it as long as we don't damage it)
* Optimization: In damageTool(), only roll the dice if there is a tool
to be damaged
* Fix: When asking a block for its drops, give it its own coordinates

Some fixes/optimizations for the TreeFarmer

---

src/main/java/crazypants/enderio/machine/farm/TileFarmStation.java

* Farming station slot shifting had an off-by-one error that destroyed
installed capacitors
* Also added some sanity checks that would have prevented item loss
Fixes bug reported in comment of #2005

Fix for Farming Station Upgrading

---

src/main/java/crazypants/enderio/item/darksteel/ItemDarkSteelArmor.java
src/main/java/crazypants/enderio/item/darksteel/ItemDarkSteelAxe.java
src/main/java/crazypants/enderio/item/darksteel/ItemDarkSteelPickaxe.java

* Dark Axe: Damage is routed the vanilla way (which does enchantment
damage reduction) and then intercepted at the "apply" stage.
Multi-harvesting is handled as direct energy use, as multi-harvesting
only works with power.
* Dark Pick: Damage is routed the vanilla way (which does enchantment
damage reduction) and then intercepted at the "apply" stage. Obsidian is
handled as additional direct energy use.
* Dark Armour: Damage is no longer set directly but routed through the
stack (which does enchantment damage reduction). This makes armor check
enchantments *after* power use.

Fix: Allow Unbreaking to work on dark steel items

---

.gitignore
build.gradle

* The new gradle task "checkTranslations" creates reports on
missing/extra lang file entries for all language files
* It is not included in the normal build process and must be run by hand
* The reports are gitgnore'ed

New gradle task to help translators

---

src/main/java/crazypants/enderio/config/Config.java
src/main/java/crazypants/enderio/machine/farm/TileFarmStation.java
src/main/java/crazypants/enderio/machine/farm/farmers/TreeFarmer.java

* New config setting for sapling reserve amount.
* When there are less than reserve amount saplings, only half the
leaves will be sheard, the other half will be harvested for saplings.
* Default is 8 (half the stacksize of the basic farming station)

Shear less when low on saplings

---

src/main/java/crazypants/enderio/config/Config.java
src/main/java/crazypants/enderio/machine/farm/TileFarmStation.java
src/main/java/crazypants/enderio/machine/farm/farmers/TreeFarmer.java

* Shearing ratio is now dynamic, between 10% at empty supply slot and
100% at the configured reserve
* Harvested seeds/sappling are added to the supply slot for the quarter
they were harvested from, then the others in order
* re #2119

More shearing tweaks

---

src/main/java/crazypants/enderio/machine/AbstractMachineEntity.java
src/main/java/crazypants/enderio/machine/farm/FarmStationContainer.java
src/main/java/crazypants/enderio/machine/farm/TileFarmStation.java

* The Farming Station's stack size limitations now actually work. Cases:
** Manual insert
** Shift-Click
** Pulling
** Pushing (e.g. item conduits)
** Harvesting
* re #2122

Fix: Stack size limits on Farming Station

---

src/main/java/crazypants/enderio/teleport/telepad/TileTelePad.java

Also changed `inNetowork` to `inNetwork()` for the coordinate getter methods.

Fixed target dimension methods in TileTelePad.java

---

src/main/java/crazypants/enderio/machine/crusher/CrusherRecipeManager.java

Very simple, just excludes block* (any oredict entry that starts with block) from grinding ball bonuses.

Duplication fix

---

src/main/java/crazypants/enderio/machine/killera/KillerJoeRenderer.java

* Moved sword a little bit to remove z-fighting with blocks in front of
the KillerJoe.
* Changed inward sword swing to use different (otherwise unused) value
than forward swing. Doesn't make a big difference either way, but I
think it looks a little bit better this way. More like swinging in a
tiny arc instead of a line.

Fix: KillerJoe Sword z-Fighting

---

src/main/java/crazypants/enderio/teleport/packet/PacketTravelEvent.java

doServerTeleport() does it, too.

Fix: TeleportEntityEvent fired twice

---

src/main/java/crazypants/enderio/conduit/TileConduitBundle.java
src/main/java/crazypants/enderio/machine/AbstractMachineEntity.java
src/main/java/crazypants/enderio/machine/AbstractPoweredMachineEntity.java
src/main/java/crazypants/enderio/machine/hypercube/TileHyperCube.java
src/main/java/crazypants/enderio/machine/killera/TileKillerJoe.java
src/main/java/crazypants/enderio/machine/power/TileCapacitorBank.java
src/main/java/crazypants/enderio/machine/reservoir/TileReservoir.java
src/main/java/crazypants/enderio/machine/solar/TileEntitySolarPanel.java
src/main/java/crazypants/enderio/machine/transceiver/TileTransceiver.java
src/main/java/crazypants/enderio/machine/wireless/TileWirelessCharger.java
src/main/java/crazypants/enderio/teleport/telepad/TileTelePad.java

They are not needed, the code calling doUpdate() would NPE if worldObj
was ever null at this point.

Cleanup: null checks in doUpdate()

---

resources/assets/enderio/config/SAGMillRecipes_Core.xml

What is done so far:
1) Basic support for Tcon (Metal blocks are not added)
2) Basic support for Nether Ores (Not all ores are added) Part of #182
3) Aluminium and Natural Aluminum support. Closes #307
4) Reworked Applied Energistics support. Need to discuss power consumption changes, maybe I should revert them? Should close #2252
5) Some other cleanup changes
Suggestions are welcome

SAG Mill support for Tcon, Nether Ores

---

src/main/java/crazypants/enderio/TileEntityEio.java
src/main/java/crazypants/enderio/config/Config.java

* Config value to have machines reject an update rate that is higher
than the global tick rate.
* Default is unchanged (allow).

New: Config value to disable upticking

---

src/main/java/crazypants/enderio/config/Config.java

I was not able to find the "level" misspells, sorry. It looks like the issue creator had a outdated configuration file, I just looked over a freshly generated file and could not locate any "level" misspells.

Fix typos in configuration file. Fixes #2440

---

src/main/java/crazypants/enderio/machine/AbstractMachineEntity.java
src/main/java/crazypants/enderio/machine/AbstractPoweredTaskEntity.java

The previous implementations calls isMachineItemValidForSlot twice which can be expensive.

optimize canInsertItem

---

src/main/java/crazypants/enderio/fluid/FluidFuelRegister.java

There is a typo in the NBT version of addFuel, so it is trying to get the "power per cycle" from the "fluid name" tag.
This method is used when mods send a `FLUID_FUEL_ADD` IMC message.

Fix FluidFuelRegister addFuel from NBT

---

src/main/java/crazypants/enderio/conduit/AbstractItemConduit.java

* When trying to place a conduit where different one of the same type already exists, this will drop the existing conduit and place the new one. (Old: do nothing)
* re #2485

Replace Conduits

---

src/main/java/crazypants/enderio/conduit/item/ItemConduitNetwork.java
src/main/java/crazypants/enderio/conduit/item/NetworkedInventory.java

While Lang.localize has a try/catch it doesn't make sense to use this class for names outside of the EnderIO resources. And sadly that try/catch did not protect against all crashes.

don't crash for unnamed inventories or when the name contains special characters

---

src/main/java/crazypants/enderio/machine/generator/combustion/TileCombustionGenerator.java

* Combustion Generator Input Tank Handling wasn't implementing the
interface correctly, leading to NPEs
* re #2584

Fix: Combustion Generator Input Tank Handling

---

src/main/java/crazypants/enderio/teleport/telepad/TileTelePad.java

* Allow coords to be set on any block of the multiblock, not just the
master
* Prevent maxPower to be 0 to prevent undefined behavior

Fix: Telepad multipart

---

resources/assets/enderio/config/SAGMillRecipes_Core.xml

Reworked version of #2418 but now without touching CoFH/Tcon stuff. Only added blocks support for existing stuff.

SAG Mill support for blocks

---

resources/assets/enderio/config/OreDictionaryPreferences_Core.xml
resources/assets/enderio/config/SAGMillRecipes_Core.xml

These also renames ore dict references from `flint` to `itemFlint` as that's what `enderio.core.common.OreDict` is registering flint as.
I'm not sure if this fully solves #2776 though: I wasn't able to reproduce the "invalid OreDictionary tag" thing.

Fix for #2751 - SAG mill producing sand with invalid metadata

---

resources/assets/enderio/config/SAGMillRecipes_Core.xml
src/main/java/crazypants/enderio/machine/recipe/RecipeConfigParser.java

* Fixed SAGMillRecipes_Core.xml; added info on how to set both values
and better path info for clarity
* Fixed parser; left old spelling for compatibility
* re #2798

Typo in XML: "RegistEry"

---

src/main/java/crazypants/enderio/machine/AbstractPoweredTaskEntity.java

This allows machines to have tasks that are complete but cannot be
finished. With this they can sit there and not use power.

Allow for machines that have tasks that stall at the end

---

src/main/java/crazypants/enderio/machine/AbstractMachineBlock.java
src/main/java/crazypants/enderio/machine/obelisk/BlockObeliskAbstract.java
src/main/java/crazypants/enderio/machine/slicensplice/BlockSliceAndSplice.java
src/main/java/crazypants/enderio/machine/soul/BlockSoulBinder.java

The side looks a bit silly on the bottom, as it has an up and a down. "machineTemplate.png"/"blockSoulMachineBlank.png" are nice and
symetrical. Should they be copied over to
"machineBottom.png"/"blockSoulMachineBottom.png"?

Use seperate texture for machine bottom

---

src/main/java/crazypants/enderio/machine/AbstractMachineBlock.java

Fall back to a sensible facing direction when there is no tileEntity.
This e.g. happens when a facade is painted as machine. Facing down won't
really render nicely---down is not a valid rotation for machines.
* re #2902 (partially)

Fall back to a sensible facing direction

---

src/main/java/crazypants/enderio/conduit/render/ConduitBundleRenderer.java
src/main/java/crazypants/enderio/enderface/GuiEnderface.java
src/main/java/crazypants/enderio/gui/IoConfigRenderer.java
src/main/java/crazypants/enderio/machine/generator/zombie/ZombieGeneratorRenderer.java
src/main/java/crazypants/util/RenderPassHelper.java

Forge stores the current render pass for blocks and tile entities in different locations. As that is not documented, it is often mixed up.
re #2862

Fix render pass mixup

---

src/main/java/crazypants/enderio/machine/farm/FakeFarmPlayer.java

This might be the cause of #2957 and #2983. About the only plausible explaination for the crash, unless someone is patching activateBlockOrUseItem() badly.

Prevent FarmerJoe from being removed from the world

---

src/main/java/crazypants/enderio/fluid/BucketHandler.java

They need to handle this event themselves. We only handle converting
vanilla buckets into Ender IO buckets.
re #2703

Ignore non-vanilla buckets firing FillBucketEvent events

---

src/main/java/crazypants/enderio/machine/vacuum/ContainerVacuumChest.java

by removing it. The ContainerEnder one does the right thing already.
Also moved filter slot to first position; so shift-clicking a filter
upgrade into the vacuum chest does the expected thing.
re #2935

Fix Vacuum Chest shift-click

---

src/main/java/crazypants/enderio/conduit/item/filter/ItemFilter.java
src/main/java/crazypants/enderio/machine/transceiver/TileTransceiver.java

The item filter is in use in the GUI. If it is replaced in the TE by the
server copy, the client will have 2 different copies of it.
re #2693

Don't replace an object that is in use elsewhere

---

src/main/java/crazypants/enderio/machine/obelisk/ObeliskRenderer.java

Having two identical top faces renders with a strange wobble because the
positions are not 100.000% identical. So only render one top face.

Fix for obelisk renderer

---

src/main/java/crazypants/enderio/conduit/ConduitRecipes.java
src/main/java/crazypants/enderio/enderface/EnderfaceRecipes.java
src/main/java/crazypants/enderio/item/ItemRecipes.java
src/main/java/crazypants/enderio/item/darksteel/DarkSteelRecipeManager.java
src/main/java/crazypants/enderio/machine/MachineRecipes.java
src/main/java/crazypants/enderio/material/Alloy.java
src/main/java/crazypants/enderio/material/MaterialRecipes.java
src/main/java/crazypants/enderio/material/PowderIngot.java
src/main/java/crazypants/enderio/thaumcraft/ThaumcraftCompat.java

* re #2839
* Legacy oreDict names are still registered
* Recipes only use the primary/new oreDict name
* Conversion recipes for items with the legacy oreDict names into EIO items (that can be used in recipes) are registered, too
* re #2945
* powders are auto-registered so it doesn't get missed when a new power is added (like it happened with flour)

OreDict modern alloy names, too

---

src/main/java/crazypants/enderio/tool/EnderIOCrashCallable.java

* Detect problems at crash time instead of load time
* Detect when Ender IO ALI is loaded from other mods
* Detect when the actually used RF API differs from the one FML reports
to be loaded (yes, this happens. Even in a clean dev env!)
* Nicer output

Make crash reporting more robust and detect more problems

---

src/main/java/crazypants/enderio/machine/alloy/VanillaSmeltingRecipe.java

re #1530
Root cause: Some mods (e.g. Biomes of Plenty) register smelting recipes with invalid XP multipliers. Vanilla ignores them.

Limit smelting XP the same way vanilla does (thx to mmelvin0)

---

src/main/java/crazypants/enderio/xp/ExperienceContainer.java

Extracting less fluid than makes up 1 XP would return that and decrement
the stored XP by 0

Prevent XP duping when converting into liquid

---

src/main/java/crazypants/enderio/config/Config.java
src/main/java/crazypants/enderio/item/KeyTracker.java

if there's a keybinding set. Also switched to enabling right click instead of wheel---that one can be toggled mid-game.
re #3154

Allow both Yeta Wrench mouse actions to be off

---

src/main/java/crazypants/enderio/machine/painter/BlockPaintedGlowstone.java

re #2789
I think that is the only painted block aside from facades that connects textures? All others aren't solid.

Keep meta when dropping painted glowstone as item

---

src/main/java/crazypants/enderio/machine/capbank/TileCapBank.java
src/main/java/crazypants/enderio/machine/power/TileCapacitorBank.java
src/main/java/crazypants/enderio/machine/tank/TileTank.java

Comparators output a zero power level both when attached to empty storage, and nearly empty storage. This makes it impossible to differentiate between the two. The new semantics in this patch are equivalent to those used by Minecraft for chests, etc.
**Before:**
**After:**

Fix zero comparator signal on near-empty storage

---

src/main/java/crazypants/enderio/config/Config.java
src/main/java/crazypants/enderio/machine/generator/stirling/GuiStirlingGenerator.java
src/main/java/crazypants/enderio/machine/generator/stirling/TileEntityStirlingGenerator.java

* Added config settings for burn time and energy multiplier
* Normalized burn rate display to base value
* Increased efficiency of octa-upgraded generator a tiny bit (6x instead
of 5.3x) to avoid oddity of having the burn time display not change with
the second upgrade
* Fixed base RF config setting not responding to runtime config changes

Made Stirling Generator more configurable

---

src/main/java/crazypants/enderio/config/Config.java
src/main/java/crazypants/enderio/item/MagnetController.java

* Limit number of items the magnet hoovers at a time
* Don't use vanilla code to select items but use our specialized, short-circuiting version of it
* also do less math. item speed is a bit different now, but not really noticable
* re #1736, #2918, #2919
* alternative to #2920

Reworked the magnet code

---

resources/assets/enderio/config/AlloySmelterRecipes_Core.xml
src/main/java/crazypants/enderio/config/Config.java
src/main/java/crazypants/enderio/machine/MachineRecipeRegistry.java
src/main/java/crazypants/enderio/machine/recipe/ManyToOneRecipeManager.java
src/main/java/crazypants/enderio/machine/recipe/OreDictionaryRecipeInput.java
src/main/java/crazypants/enderio/machine/recipe/RecipeConfig.java
src/main/java/crazypants/enderio/machine/recipe/RecipeConfigParser.java
src/main/java/crazypants/enderio/nei/AlloySmelterRecipeHandler.java

* Single input alloy smelter recipes now will get multi-slot variants
added automatically
* There's a config flag to disable this
* Removed existing partila multi-slot recipes
* Fixed code that depends on the order of recipes in a HashMap
* Fixed code that depends on the order of machineRecipes in a HashMap
re #3026, #1070
Note: We still have a problem with recipes that need only a single item but more than 1 of it. So the 4xnetherQuartz one will fail on an input of "64/1/0". And if there is a vanilla recipe available for smelting netherQuartz, it will take over.
To fix this, we'd need to replace large parts of the recipe system.

Improve handling of single-input recipes

---

src/main/java/crazypants/enderio/conduit/gui/GuiExternalConnectionSelector.java

Its been a year, since #1984, so i thought i might give it a shot.
For 1.7.10. I hope you still accept PRs for it and that it can be easily ported to 1.9.8 and above.

Show Block Name in GuiExternalConnectionSelector. Fixes #1984

---

src/main/java/crazypants/enderio/machine/farm/TileFarmStation.java
src/main/java/crazypants/enderio/machine/farm/farmers/MelonFarmer.java

* Prevent Farm becoming stuck if 20 or more blocks are in an unloaded chunk **or on itself**
* Fix MelonFarmer not working for parts of the farm that are on the other side of the X=0 or Z=0 border

Small Fixes for the Farm (actually one big one, too)

---

.gitignore
gradle.properties
src/main/java/crazypants/enderio/EnderIO.java
src/main/java/crazypants/enderio/integration/jei/AlloyRecipeCategory.java
src/main/java/crazypants/enderio/integration/jei/CombustionRecipeCategory.java
src/main/java/crazypants/enderio/integration/jei/DarkSteelUpgradeRecipeCategory.java
src/main/java/crazypants/enderio/integration/jei/EnchanterRecipeCategory.java
src/main/java/crazypants/enderio/integration/jei/PainterRecipeCategory.java
src/main/java/crazypants/enderio/integration/jei/RecipeWrapper.java
src/main/java/crazypants/enderio/integration/jei/SagMillRecipeCategory.java
src/main/java/crazypants/enderio/integration/jei/SliceAndSpliceRecipeCategory.java
src/main/java/crazypants/enderio/integration/jei/SoulBinderRecipeCategory.java
src/main/java/crazypants/enderio/integration/jei/TankRecipeCategory.java
src/main/java/crazypants/enderio/integration/jei/VatRecipeCategory.java
src/main/java/crazypants/enderio/machine/vat/VatRecipe.java

The JEI update to 3.11.x is a big refactor and broke EnderIO integration (you are using some internal classes).
This PR updates the integration, moves away from deprecated methods, and sets the minimum JEI version to 3.11.1.

Update Integration for JEI version 3.11.x

---

src/main/java/crazypants/enderio/EnderIO.java

With fluids being registered before items are created, `ItemRodOfReturn` can't find `ender_distillation`, which leads to an NPE when attempting to render the item, in say, the creative tab.
```
[04:04:38] [Client thread/WARN] [EnderIO/EnderIO]: ItemRodOfReturn: Could not find fluid 'ender_distillation' using default fluid null
```
```
Description: Rendering screen
java.lang.IllegalArgumentException: Cannot create a fluidstack from a null fluid
at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:47)
at crazypants.enderio.teleport.telepad.ItemRodOfReturn.getFluid(ItemRodOfReturn.java:418)
at crazypants.enderio.teleport.telepad.ItemRodOfReturn$FluidCapabilityProvider$1.getContents(ItemRodOfReturn.java:469)
at crazypants.enderio.item.PowerBarOverlayRenderHelper$FluidBarOverlayRender …
```

register fluids before items

---

src/main/java/crazypants/enderio/conduit/redstone/ISignalProvider.java
src/main/java/crazypants/enderio/conduit/redstone/InsulatedRedstoneConduit.java

Until we have a proper API, this is better than nothing.
[Example implementation](https://github.com/Vexatos/OpenComputers/blob/6601aad34d8487330b95e311c0c0eae58b21e3b6/src/main/scala/li/cil/oc/integration/enderio/ProviderEnderIO.scala#L51-L67). Tested with that and it appears to be working just fine.
Also made `getNetworkOutputs` report all signals to a special connection instead of just one. [Used for getting the bundled network output](https://github.com/Vexatos/OpenComputers/blob/6601aad34d8487330b95e311c0c0eae58b21e3b6/src/main/scala/li/cil/oc/integration/enderio/ProviderEnderIO.scala#L34-L49).

Added a way to register custom signal providers for Insulated Redstone Conduits.

---

src/main/java/crazypants/enderio/machine/farm/farmers/HempFarmerIE.java

Actually EnderIO's farmer havresting Immersive Engineering's Industrial Hemp wrong: it harvest base block too (in addition to upper block). It causes re-plant loop and additional waiting time.
How it works now:
How it should works:

Fix Immersive's hemp haversting

---

build.gradle

Changed all `HashMap`s to `LinkedHashMap`s so the language keys are stored in the maps in order which in turns outputs them in the translation report in order as well. This simplifies the translation process

Improved checkTranslations task

---

src/main/java/crazypants/enderio/LootManager.java
src/main/java/crazypants/enderio/capacitor/LootSelector.java

See title. This fixes the issue discussed in #3927 
Loot weights will need to be adjusted as the loot weight system behaves differently to the previous probability based system. I tried to do this myself mathematically and failed due to differences between the two systems. The values will have to be adjusted by a process of guess and check, or something better if anyone knows of it.
A test world that can be used to easily test the loot tables can be found [here](https://drive.google.com/open?id=0B_IqTUgN98IXaVdjV0JtcFphZU0).
The world contains 4 buttons that each place a chest that uses one of the four loot tables modified by EnderIO.

Rewrite LootManager to use a standard Loot Table. Closes #3927

---

src/main/java/crazypants/enderio/conduit/BlockConduitBundle.java

When Crouch-Left-Clicking conduit bundles to get the GUI up, it only checks for a Yeta wrench, is it acceptable to extend this to all ITool implementations?
I've implemented ITool on my item and would really love to have this functionality (beyond waiting for the block to finish breaking in survival before I cancel it and manually bring up the GUI).

Request - Check ToolUtil for equipped tool rather than just YetaWrench Item

---

src/main/java/crazypants/enderio/fluid/BlockFluidEio.java

Modified the teleportation for molten ender to trigger an event as if an ender pearl has been thrown for the teleportation of a mob/player. I did this mainly to work with the Dark Utils Ender Tether as it adjusts the teleport destination based on the EnderTeleportEvent. Teleport still behaves as normal and random if there is nothing that intercepts the event.

Modified Molten Ender Teleport

---

src/main/java/crazypants/enderio/machines/machine/generator/combustion/BlockCombustionGenerator.java

Fixes the issue where the Combustion Generator tile entity was not receiving neighbor updates (neighborChanged) not being called.

Fix Combustion Generator updating (Fixes #4396)

---

src/main/java/crazypants/enderio/machines/machine/buffer/TileBuffer.java

Fixes the issue where the power buffer was not updating its PowerDistributor when placing adjacent machines.

Fixed power buffer not updating

---

src/main/java/crazypants/enderio/base/item/darksteel/ItemDarkSteelPickaxe.java
src/main/java/crazypants/enderio/base/item/darksteel/upgrade/energy/EnergyUpgradeManager.java
src/main/java/crazypants/enderio/util/NbtComparer.java

Fixed the issue where the pickaxe (or any other tool) will be interrupted while it's being charged by a wireless charger.
The issue was happening because the default behavior was to reset block break progress on and `ItemStack` change, that includes NBT which is used to store the tools' energy.
The current implementation tries to as strict as possible when it comes to resetting the progress. This is done by running a deep equality comparison of the old and new NBT trees while ignoring the `energy` key.
I'm not a big fan of the current state of things though, feel free to suggest a different approach.
What I had in mind was:
* Store the energy value on an internal variable and to (re)store it from/to NBT when needed. Not sure how to do this. And client-server sync may be a problem.
* …

Fixed pickaxe interrupting while charging

---

resources/assets/enderio/lang/en_us.lang

Removed the creative tab name for the machines tab, so it can be put into the enderio base lang file. (where the code is that creates the creative tabs)

Remove Name

---

build.gradle

Fixed a problem where the dependency replacement ran before the
replacement target was configured.

Fixed bad configuration ordering in build

---

build.gradle
enderio-base/dependencies.gradle
enderio-base/enderio-base.gradle
enderio-base/gradle.properties
enderio-conduits/dependencies.gradle
enderio-conduits/enderio-conduits.gradle
enderio-conduits/gradle.properties
enderio-invpanel/dependencies.gradle
enderio-invpanel/enderio-invpanel.gradle
enderio-invpanel/gradle.properties
enderio-machines/dependencies.gradle
enderio-machines/enderio-machines.gradle
enderio-machines/gradle.properties

Modified some project configuration ordering to allow modules to easily
depend on each other. Dependencies are now defined in
`dependencies.gradle'.

Modules now depend on each other

---

build.gradle
enderio-base/gradle.properties
enderio-conduits/gradle.properties
enderio-invpanel/gradle.properties
enderio-machines/gradle.properties

Made a few fixes and enhancements for the build script.
* Every build with BUILD_NUMBER defined will be considered 'CI' build
* Changed the NIGHTLY classifier to lowercase (was by mistake UC)
* Source and Api jars are only published for projects with 'publish_X'
* Made the task 'killer' less aggresive.

Some fixes and enhancements for the build script

---

enderio-base/src/main/java/crazypants/enderio/base/machine/baselegacy/AbstractPoweredTaskEntity.java
enderio-machines/src/main/java/crazypants/enderio/machines/machine/soul/TileSoulBinder.java

Temperary fix for the soul binder (can now only craft if the output slot is empty (prevents soul vial (bat) + broken spawner from creating a slime spawner if a slime spawner is already in that slot)).  canStartNextTask (should) check if the recipe output is equal to the item in the output slot or if the slot is empty.

Sould Binder Fix

---

enderio-base/src/main/java/crazypants/enderio/api/IMC.java
enderio-base/src/main/java/crazypants/enderio/api/redstone/IRedstoneConnectable.java
enderio-base/src/main/java/crazypants/enderio/api/redstone/IRedstoneConnectable_dont_crash_us_mcjty.java
enderio-base/src/main/java/crazypants/enderio/api/redstone/package-info.java
enderio-base/src/main/java/crazypants/enderio/base/conduit/redstone/ConnectivityTool.java
enderio-base/src/main/java/crazypants/enderio/base/machine/base/te/AbstractMachineEntity.java
enderio-conduits/src/main/java/crazypants/enderio/powertools/machine/capbank/BlockCapBank.java
enderio-machines/src/main/java/crazypants/enderio/machines/machine/light/BlockElectricLight.java
enderio-machines/src/main/java/crazypants/enderio/machines/machine/vacuum/BlockVacuumChest.java

I fixed McJtyLib to not bundle our API, so upgrading to McJtyLib 2.5.2 makes this no longer necessary.

Revert hack to fix McJtyLib crashing us

---

build.gradle
enderio-conduits/enderio-conduits.gradle
enderio-conduits/gradle.properties
enderio-conduits/src/main/java/crazypants/enderio/conduits/conduit/redstone/InsulatedRedstoneConduit.java
enderio-conduits/src/main/java/crazypants/enderio/conduits/init/CommonProxy.java
enderio-conduits/src/main/java/crazypants/enderio/conduits/integration/computercraft/CCUtil.java
enderio-conduits/src/main/java/crazypants/enderio/conduits/integration/computercraft/ConduitBundledRedstoneProvider.java

Effectively cherry-picked from #1208. I'm not sure if this is a) wanted and b) how mod integration is meant to be handled, so feel free to close it :).
One thing worth noting is that `IRedstoneConduit.getNetworkOutputs` has the side parameter annotated as `@Nonnull`, but handles `null` arguments (which is required here in order to return the signal for all colours).

Re-add ComputerCraft bundled cable integration

---

enderio-machines/src/main/resources/assets/enderio/config/recipes/sagmill_ores.xml

Oredict name changed without warning in thermal
Also adds new RED Sand Varient to oil shale processing

Fix Thermal Expansion Fluids

---

enderio-base/src/main/resources/assets/enderio/config/recipes/examples/legacy_recipes.xml

For people who really don't like change.
Reverts most crafting recipes back to their 1.10 (or earlier) versions.  Unless specified, new 1.12 content is left unchanged.
Changed the alias of Grains of Infinity to Redstone.  This currently doesn't work, but should replace Grains with Redstone in the future.
Disabled Simple Machines, and the unused Machine Dyes and Photovoltaic crafting components.
Added recipes for the Simple Photovoltaic Cell, Soul Chassis, and Enhanced Chassis.
Note that the gears and Simple Chassis can still be crafted to ensure future compatibility.
Currently, all non-enhanced machines use Industrial Chassis.  The machines that would normally use Soul Chassis have the `````` comment next to them.

Added Legacy Recipes to Examples Folder

---

enderio-conduits/src/main/java/crazypants/enderio/conduits/gui/LiquidSettings.java

A fix to stop tooltips for filter / upgrade slots displaying in non-ender liquid conduit guis.  There are no filter / upgrade slots for the non ender liquid conduit varieties.

Fixed tooltips displaying in non ender liquid conduits

---

enderio-conduits-appliedenergistics/src/main/java/crazypants/enderio/conduits/me/conduit/ItemMEConduit.java
enderio-conduits-opencomputers/src/main/java/crazypants/enderio/conduits/oc/conduit/ItemOCConduit.java
enderio-conduits-refinedstorage/src/main/java/crazypants/enderio/conduits/refinedstorage/conduit/ItemRefinedStorageConduit.java

When all the conduits are placed in the same bundle without any of them connecting to another spot the 3 non default conduits (ME, RS, and OC) positioning looks off due to being in a different plane than the 4 base ones.
How it is currently: https://i.gyazo.com/b5be7ef20d5fc0a08f5c638049ebb34e.png
How it looks after these changes: https://i.gyazo.com/450dd22da070d784b8b2f30d57019969.png
All bundle rendering looks the same as it is currently is, this just changes how it appears when they have no connectors.

Made unconnected conduit bundles be in one plane

---

enderio-conduits-appliedenergistics/src/main/java/crazypants/enderio/conduits/me/conduit/ItemMEConduit.java
enderio-conduits-opencomputers/src/main/java/crazypants/enderio/conduits/oc/conduit/ItemOCConduit.java
enderio-conduits-refinedstorage/src/main/java/crazypants/enderio/conduits/refinedstorage/conduit/ItemRefinedStorageConduit.java

This change saves a small amount of memory space in the conduitRenderers list as there are not 3 more instances of the DefaultConduitRenderer object in memory. [ConduitBundleRenderer#getRendererForConduit()](https://github.com/SleepyTrousers/EnderIO/blob/master/enderio-conduits/src/main/java/crazypants/enderio/conduits/render/ConduitBundleRenderer.java#L298) already defaults to the DefaultConduitRenderer. 
More importantly however, it makes it easier/cleaner for addons adding their own Conduit Rendering as they do not have to add `before:enderioconduitsappliedenergistics;before:enderioconduitsopencomputers;before:enderioconduitsrefinedstorage;` to their dependency list just to ensure their renderer gets used. The reason that the loading before is currently required is because the …

Don't manually register the DefaultConduitRenderer

---

enderio-base/src/main/resources/assets/enderio/config/recipes/misc.xml

Some mods add items like trapped chests to chestWood, so I think it's better for all the recipes to craft the vanilla items instead of an OreDict entries (for all 3, just in case), as with No More Recipe Conflicts it would be possible to craft 4 trapped chests from 8 logs or anything else added to the Ore Dictionary that we don't expect.

Fix issue with No More Recipe Conflicts

---

enderio-machines/src/main/resources/assets/enderio/config/recipes/examples/cheaty_spawner.xml

Overhauled cheaty_spawner.xml to work with the current recipe system.
Added Snow Golem spawners with a cost multiplier of 100 to match Villagers and Iron Golems.
Added comments to the top explaining what the example does, pointing out that the Ender Dragon isn't possible, and the normal activation instructions.

Make cheaty_spawner.xml Example Usable

---

enderio-zoo/src/main/java/crazypants/enderio/zoo/entity/EntityOwl.java

Seems that vanilla collision code doesn't play nice when an entities eye height is the same as the entities full height, this fixes that.
The real fix is the change in the getEyeHeight method, using F3+b you can see the eye height is matched better to the actual owls eyes.
The rest of the code removed is code that attempted to fix this issue which is no longer relevant, removed it within this PR because it felt in scope enough to do so.
Side note: The copied and modified isEntityInsideOpaqueBlock() from an earlier minecraft version and then ported to 1.12 had an additional issue of not updating the use of isOpaqueCube() in it, vanilla 1.12 uses causesSuffocation(), that missing adjustment caused leafs to do damage when they should not, thats all redundant now anyways.

Fix owls getting damage when pressing against block above them

---

enderio-zoo/src/main/java/crazypants/enderio/zoo/entity/ai/EntityAIMountedAttackOnCollide.java

First commit fixes a clear bug from porting, shouldContinueExecuting was never executing. This stopped the knight from standing still for 3-4 seconds before continuing to chase you.
Second commit puts the pathing delays more in line with vanilla. Fast enough to track well, but delayed enough to make it not thrash the pathfinder. This resulted in the knight continuing to track you instead of pathing to where you previously were.
I left the path penalty code in shouldExecute because its a good improvement that IMO vanilla zombies should have as well.
Note this doesnt fix the mounted knight spinning in a circle bug, that's a different issue I will do in a different PR.

Fix fallen knight not tracking player tightly enough

---

enderio-zoo/src/main/java/crazypants/enderio/zoo/entity/EntityFallenKnight.java
enderio-zoo/src/main/java/crazypants/enderio/zoo/entity/navigate/PathNavigateGroundMounted.java

So mounted pathfinding is a tricky thing. The entity on top does the pathfinding work, and also runs the pathfollowing code but instead the entity on the bottom follows the path, in this case, a larger horse/mount. This can cause some... issues. This PR isn't perfect and should definitely be tested to see if it feels like it helps overall (I suggest testing with my other PRs to so the pathing is much faster)
My primary goal was to fix horses/mounts spinning with the fallen knight on top of them when they are trying to drop down a block. Most often when its a diagonal drop down from an upper L shape of blocks is when it happens.
This makes the y difference more relaxed when it detects the right conditions, as best I can tell this doesn't introduce any side affects, but you guys might spot …

Improve fallen mount with knight riding pathfollowing, fixes spinning horse

---

enderio-base/src/main/java/crazypants/enderio/util/CapturedMob.java

This makes it possible to use Spawn Eggs to set the entity in the Soul Filter. (Including via dragging from JEI to the ghost slot as it is just a normal ItemStack)
The side effect of this change, is that you can use Spawn Eggs in place of soul vials in obelisks. (Does not change any other location.)
I believe this is fine, as there are no real recipes for Spawn eggs anyways. (Currently the obelisks support both broken spawners and soul vials.

Make captured mob support spawn eggs

---

enderio-conduits/src/main/java/crazypants/enderio/conduits/conduit/liquid/EnderLiquidConduitNetwork.java

Sort the tanks list whenever the connection is changed.

Fix conduit connector losing priority on unrelated connection changes

---

enderio-machines/src/main/java/crazypants/enderio/machines/machine/tank/TileTank.java

Fixes an issue where ThermalCultivation's Watering Cans, when empty, go into the "drain" slot both via automation and GUI shift-click, preventing the can from being automatically refilled. (It remains in that slot forever.)

Tanks consider containers of zero-sized fluid stacks as empty

---

enderio-base/src/main/java/crazypants/enderio/base/teleport/TravelController.java

Fixes #4773 
Requires change in EnderCore, which is in this related [pull request #109 for EnderCore](https://github.com/SleepyTrousers/EnderCore/pull/109)
When Optifine or other graphics mods are installed, Tileentities may be rendered even when not in the current frustum. This causes us to be able to teleport to travel anchors that are behind the player, which makes travelling with them really cumbersome.
This PR fixes this by manually culling points by their projected Z coordinate.
Disclaimer:
Unfortunately I could not test this change locally, as some unrelated parts of EnderIO fail to compile on my machine (my java "OpenJDK IcedTea 3.11.0" is more strict about several things like abstract classes etc.). While this is a small change, I could possibly have mistaken +Z and -Z for …

Fixed selection of travel anchor locations when rendered behind the player

---

enderio-endergy/src/main/java/crazypants/enderio/endergy/capacitor/ItemTotemicCapacitor.java

the name of the efficiency enchantment in minecraft is actually "enchantment.digging", not "efficiency", so any attempt to enchant it in survival would fail as that check would never pass.
Closes #5057

Fix totemic capacitors not being able to be enchanted with efficiency and odd levels of efficiency being rounded down
